BEGIN;
--
-- Create model Comment
--
CREATE TABLE "blog_comments" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "content" text NOT NULL, "object_id" integer NOT NULL CHECK ("object_id" >= 0), "created_at" timestamp with time zone NOT NULL, "modified_at" timestamp with time zone NOT NULL, "content_type_id" integer NOT NULL, "creator_id" integer NOT NULL);
--
-- Create model Post
--
CREATE TABLE "blog_posts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "last_modified_at" timestamp with time zone NOT NULL, "published_at" timestamp with time zone NULL, "title" varchar(100) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "summary" text NOT NULL, "content" text NOT NULL, "status" varchar(1) NOT NULL, "author_id" integer NOT NULL);
--
-- Create model Tag
--
CREATE TABLE "blog_tags" ("value" text NOT NULL PRIMARY KEY, "_order" integer NOT NULL);
--
-- Create constraint unique_lower_name_tag on model tag
--
CREATE UNIQUE INDEX "unique_lower_name_tag" ON "blog_tags" ((LOWER("value")) DESC);
--
-- Add field tags to post
--
CREATE TABLE "blog_posts_tags" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "post_id" bigint NOT NULL, "tag_id" text NOT NULL);
--
-- Create index post_author on field(s) author of model post
--
CREATE INDEX "post_author" ON "blog_posts" ("author_id");
--
-- Create index posts_status on field(s) status of model post
--
CREATE INDEX "posts_status" ON "blog_posts" ("status");
ALTER TABLE "blog_comments" ADD CONSTRAINT "blog_comments_content_type_id_a5131f0b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "blog_comments" ADD CONSTRAINT "blog_comments_creator_id_be059264_fk_auth_user_id" FOREIGN KEY ("creator_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_comments_content_type_id_a5131f0b" ON "blog_comments" ("content_type_id");
CREATE INDEX "blog_comments_creator_id_be059264" ON "blog_comments" ("creator_id");
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_author_id_6f561d00_fk_auth_user_id" FOREIGN KEY ("author_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_posts_slug_93227477_like" ON "blog_posts" ("slug" varchar_pattern_ops);
CREATE INDEX "blog_posts_author_id_6f561d00" ON "blog_posts" ("author_id");
CREATE INDEX "blog_tags_value_724c05a6_like" ON "blog_tags" ("value" text_pattern_ops);
CREATE INDEX "tag_value" ON "blog_tags" ("value");
ALTER TABLE "blog_posts_tags" ADD CONSTRAINT "blog_posts_tags_post_id_tag_id_7fdace16_uniq" UNIQUE ("post_id", "tag_id");
ALTER TABLE "blog_posts_tags" ADD CONSTRAINT "blog_posts_tags_post_id_32404083_fk_blog_posts_id" FOREIGN KEY ("post_id") REFERENCES "blog_posts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "blog_posts_tags" ADD CONSTRAINT "blog_posts_tags_tag_id_be8ac458_fk_blog_tags_value" FOREIGN KEY ("tag_id") REFERENCES "blog_tags" ("value") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_posts_tags_post_id_32404083" ON "blog_posts_tags" ("post_id");
CREATE INDEX "blog_posts_tags_tag_id_be8ac458" ON "blog_posts_tags" ("tag_id");
CREATE INDEX "blog_posts_tags_tag_id_be8ac458_like" ON "blog_posts_tags" ("tag_id" text_pattern_ops);
COMMIT;
