name: General Test and Deploy 
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code Checkout
        uses: 'Actions/Checkout@v3'
      - name: Install Dependencies 
        run: |
          python3 venv . 
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install 
      - name: Run Tests
        run: make testsgit 
          