name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Prints greeting
        run: echo "Hello World"
      - name: Prints goodbye
        run: echo "That's All Folks!"
